# Generated by Django 4.0.2 on 2022-02-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_orders_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='address',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
