# Generated by Django 4.0.2 on 2022-02-20 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_brand_product_category_product_sub_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sub_category',
        ),
    ]
