# Generated by Django 4.0.2 on 2022-02-21 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_product_category_product_sub_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='orders',
        ),
    ]
