# Generated by Django 4.0.2 on 2022-02-22 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_orders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='orders',
        ),
    ]
